### PR TITLE
use systemd for start/ stop via browser

### PR DESCRIPTION
**Pull request by basti122303**
this **only** for non debug mode, I never used it.

create a sudoers file like:
`# /etc/sudoers.d/www-data`
`www-data ALL=(root) NOPASSWD: /usr/bin/systemctl restart 123solar.service`
`www-data ALL=(root) NOPASSWD: /usr/bin/systemctl stop 123solar.service`
`www-data ALL=(root) NOPASSWD: /usr/bin/systemctl start 123solar.service`

### CODE REVIEW

**Comment by jeanmarc77** [comment]
I like the idea but well, i'm not sure..
Systemd is not a 123s requirement  (some people NAS or whatever..)
Also, people will have additional commands to do so

**Comment by basti122303** [comment]
Please add a note that when the systemd unit is used, a sudoers file is needed.

**Comment by jeanmarc77** [comment]
Hi,
I am doing some testing: The 123solar service respawn but don't write 123solar.pid file. The path is correct, i don't know what's wrong..
So, i can have several 123solar.php instances (like via the interface and from the respawn)
Can you help ?

**Comment by basti122303** [comment]
perhaps an permission problem?

have you seen 
https://github.com/jeanmarc77/123solar/pull/52/commits/2fdbfb0b8fec153523f1f5505fd6c87e655ac57e#diff-8e20415679370934cee69bc0ed071827d4e83241362259f9ddbc715e2f6f93fd
you need also edit your sudoers file
to check if the service is enabled.

**Comment by jeanmarc77** [comment]
Hi,
I have this
# This file should placed in /etc/sudoers.d/ as www-data or something else
# Username (http, www-data,..) should be edited for your needs
http ALL=(root) NOPASSWD: /usr/bin/systemctl restart 123solar.service
http ALL=(root) NOPASSWD: /usr/bin/systemctl stop 123solar.service
http ALL=(root) NOPASSWD: /usr/bin/systemctl start 123solar.service
http ALL=(root) NOPASSWD: /usr/bin/systemctl is-enabled 123solar.service

but this don't work 
<?php
exec("sudo systemctl is-enabled 123solar.service",$output);
if (is_dir('/run/systemd/system') && ($output[0] == "enabled")) {
echo 'yeah enabled';
} else {
echo 'nope';
}
?>
any idea ? how to check if sudoers is enable ?
Thanks for helping

**Comment by basti122303** [comment]
```
root@c2:~# sudo -u www-data -s /bin/bash

www-data@c2:/root$ systemctl status 123solar.service
● 123solar.service - 123Solar
     Loaded: loaded (/etc/systemd/system/123solar.service; enabled; preset: enabled)
     Active: active (running) since Fri 2023-07-07 14:09:08 CEST; 3 days ago
    Process: 32543 ExecStartPost=/bin/sh -c systemctl show -p MainPID --value 123solar.service  > /home/www/solar/scripts/123solar.pid (code=exited, status=0/SUCCESS)
   Main PID: 32542 (php)
      Tasks: 1 (limit: 2110)
     Memory: 5.5M
        CPU: 58min 41.056s
     CGroup: /system.slice/123solar.service
             └─32542 /usr/bin/php 123solar.php
www-data@c2:/root$

www-data@c2:/root$ sudo systemctl stop 123solar.service
www-data@c2:/root$

www-data@c2:/root$ systemctl status 123solar.service
○ 123solar.service - 123Solar
     Loaded: loaded (/etc/systemd/system/123solar.service; enabled; preset: enabled)
     Active: inactive (dead) since Tue 2023-07-11 13:10:12 CEST; 12s ago
   Duration: 3d 23h 1min 4.614s
    Process: 32542 ExecStart=/usr/bin/php 123solar.php (code=killed, signal=TERM)
    Process: 32543 ExecStartPost=/bin/sh -c systemctl show -p MainPID --value 123solar.service  > /home/www/solar/scripts/123solar.pid (code=exited, status=0/SUCCESS)
    Process: 13057 ExecStopPost=/usr/bin/rm -f /home/www/solar/scripts/123solar.pid (code=exited, status=0/SUCCESS)
   Main PID: 32542 (code=killed, signal=TERM)
        CPU: 58min 41.235s
www-data@c2:/root$

www-data@c2:/root$ sudo systemctl start 123solar.service
www-data@c2:/root$

www-data@c2:/root$ systemctl status 123solar.service
● 123solar.service - 123Solar
     Loaded: loaded (/etc/systemd/system/123solar.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-07-11 13:10:35 CEST; 2s ago
    Process: 13067 ExecStartPost=/bin/sh -c systemctl show -p MainPID --value 123solar.service  > /home/www/solar/scripts/123solar.pid (code=exited, status=0/SUCCESS)
   Main PID: 13066 (php)
      Tasks: 1 (limit: 2110)
     Memory: 5.2M
        CPU: 453ms
     CGroup: /system.slice/123solar.service
             └─13066 /usr/bin/php 123solar.php
www-data@c2:/root$ 
```

**Comment by basti122303** [comment]
```
www-data@c2:/etc/sudoers.d$ ls -la
total 16
drwxr-xr-x  2 root root 4096 Jul  6 22:35 .
drwxr-xr-x 88 root root 4096 Jul  8 05:46 ..
-r--r-----  1 root root 1096 Mar  8 21:17 README
-rw-r--r--  1 root root  294 Jul  6 16:37 www-data
www-data@c2:/etc/sudoers.d$ 
```

**Comment by jeanmarc77** [comment]
That sat i can request systemctl is-enabled as http without password but it dosen't work from my test script from browser.. i am lost 
[jeanmarc@zbox scripts]$ sudo -u http -s /bin/bash
[sudo] Mot de passe de jeanmarc : 
[http@zbox scripts]$ sudo systemctl is-enabled 123solar.service
enabled

**Comment by basti122303** [comment]
```
root@c2:~# whereis systemctl
systemctl: /usr/bin/systemctl /usr/share/man/man1/systemctl.1.gz
root@c2:~# 
```

**Comment by jeanmarc77** [comment]
weird, it works from CLI as http user and 123solar.service is enable

```
[jeanmarc@zbox scripts]$ LANG=C.UTF-8
[jeanmarc@zbox scripts]$ sudo -u http -s /bin/bash
[http@zbox scripts]$ sudo systemctl is-enabled 123solar.service
enabled
[http@zbox scripts]$ systemctl is-enabled 123solar.service
enabled
```

Now, if i make this test.php, i get 'nope' from browser
```
<?php
exec("sudo systemctl is-enabled 123solar.service",$output);
if ($output[0] == "enabled") {
echo 'yeah enabled';
} else {
echo 'nope';
}
?>
```

**Comment by basti122303** [comment]
```
www-data@c2:/tmp$ sudo systemctl is-enabled 123solar.service
enabled

www-data@c2:/tmp$ cat test.php 
<?php
exec("sudo systemctl is-enabled 123solar.service",$output);
if ($output[0] == "enabled") {
echo 'yeah enabled';
} else {
echo 'nope';
}
?>
www-data@c2:/tmp$ php test.php 
yeah enabled

www-data@c2:/tmp$ php -v
PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

www-data@c2:/tmp$ cat /etc/issue
Debian GNU/Linux 12 \n \l
```
modified version:
```
www-data@c2:/tmp$ php test.php 
array(1) {
  [0]=>
  string(7) "enabled"
}
www-data@c2:/tmp$ cat test.php 
<?php
exec("sudo systemctl is-enabled 123solar.service",$output);
var_dump($output);
exit();
?>
www-data@c2:/tmp$
```

**Comment by jeanmarc77** [comment]
yeah but put test.php in your webserver's directory and request test.php from a browser..

**Comment by basti122303** [comment]
```
www-data@c2:/home/www/solar$ cat test.php 
<?php
exec("sudo systemctl is-enabled 123solar.service",$output);
var_dump($output);
exit();

if ($output[0] == "enabled") {
echo 'yeah enabled';
} else {
echo 'nope';
}
?>
www-data@c2:/home/www/solar$ 
```


Unbenannt

**Comment by jeanmarc77** [comment]
damn.. i got array(0) { }

jui 11 16:05:21 zbox sudo[2188888]:     http : command not allowed ; PWD=/srv/http/123solar/scripts ; USER=root ; COMMAND=systemctl is-enabled 123solar.service
jui 11 16:05:19 zbox sudo[2188888]: pam_unix(sudo:auth): auth could not identify password for [http]
jui 11 16:05:19 zbox sudo[2188888]: pam_unix(sudo:auth): conversation failed
jui 11 16:05:19 zbox sudo[2188888]: pam_systemd_home(sudo:auth): Not a user managed by systemd-homed: No home for user http known
jui 11 16:04:21 zbox sudo[2183209]: pam_unix(sudo:session): session closed for user root
jui 11 16:04:07 zbox sudo[2183209]: pam_unix(sudo:session): session opened for user root(uid=0) by jeanmarc(uid=1000)

**Comment by basti122303** [comment]
```
www-data@c2:/home/www/solar$ echo $HOME
/var/www
www-data@c2:/home/www/solar$ grep www-data /etc/passwd
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
www-data@c2:/home/www/solar$ 
```
Which OS do you use?

**Comment by jeanmarc77** [comment]
`
[jeanmarc@zbox scripts]$ sudo -u http -s /bin/bash
[sudo] password for jeanmarc: 
[http@zbox scripts]$ echo $HOME
/srv/http
[http@zbox scripts]$ grep http /etc/passwd
http:x:33:33::/srv/http:/usr/bin/nologin
[http@zbox scripts]$ uname -a
Linux zbox 6.4.2-3-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jul  7 19:19:45 UTC 2023 x86_64 GNU/Linux
`

**Comment by basti122303** [comment]
SE Linix or apparmor?
I have no idea anymore

**Comment by falkiy** [comment]
@jeanmarc77 delete system and exec in disable_functions in your php.ini of the Webserver (means allow it)
exec means php can execute shell-commands and system means execute + Output

**Comment by jeanmarc77** [comment]
Thanks for the tips but disable_functions is empty in my php.ini.. still wondering what's wrong here

**Comment by falkiy** [comment]
for testing, in the sudoers

http ALL=(ALL) NOPASSWD: ALL

any change? sound like some wired sudo-problem/stuff

btw: would you mind to test with some fresh Debian-Container or something? We've no idea how your Machine ist configured exactly und Manjaro is absolutly not invented for Servers purposes

**Comment by falkiy** [comment]
Other Idea @basti122303 :
Let php only touch the pid and Trigger systemd path unit / incrond to stop / start the service.
Wouldn be less wired, but would prevent the sudo-stuff

**Comment by basti122303** [comment]
https://stackoverflow.com/questions/57657645/pam-unixsudoauth-conversation-failed-auth-could-not-identify-password-for
fix the first part of the error message.
The command is still not allowed.
I'am not shure if it is arch / manjaro specific, on debian there where no problems.

**Comment by basti122303** [comment]
The errors of systemd-homed not relevant here.
This is the problem:
`jui 12 16:38:50 zbox sudo[290969]: http : command not allowed ; PWD=/srv/http/123solar/admin ; USER=root ; COMMAND=systemctl stop 123solar.service`
I wrote about that above.

**Pull request merged**
